export default {
    antet: [
        "Facultatea",
        "Ciclul de studii",
        "Forma de invatamant",
        "Programul de studii",
        "Ani",
    ],

    facultati: [
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Autovehicule rutiere",
        },
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Autovehicule rutiere (în limba engleză)",
        },
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria transporturilor și a traficului",
        },
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie mecanică",
        },
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Autovehicule rutiere",
        },
        {
            ani: 4,
            fac: "01 Inginerie Mecanică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Inginerie mecanică",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Autovehiculul și mediul",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Autovehiculul și tehnologiile viitorului",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie virtuală în proiectarea autovehiculelor",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Metode practice integrate in ingineria sistemelor de propulsie",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Securitate rutieră, transport și interacțiunea cu mediul",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Simulare și testare în inginerie mecanică",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme de comandă și control pentru autovehicule",
        },
        {
            ani: 2,
            fac: "01 Inginerie Mecanică",
            cic: "Master",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Autovehiculul și mediul",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Inginerie economică industrială",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Construcții aerospațiale",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria și managementul afacerilor",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria și managementul calității",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie economică industrială",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme de producție digitale",
        },
        {
            ani: 4,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologia construcțiilor de mașini",
        },
        {
            ani: 2,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria fabricației inovative",
        },
        {
            ani: 2,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria proceselor de fabricație avansate",
        },
        {
            ani: 2,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie și management în aviație",
        },
        {
            ani: 2,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Managementul afacerilor în industrie",
        },
        {
            ani: 2,
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Managementul calității",
        },
        {
            ani: 4,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Antreprenoriat în ingineria materialelor",
        },
        {
            ani: 4,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria securității în industrie",
        },
        {
            ani: 4,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria sudării",
        },
        {
            ani: 4,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie economică în domeniul mecanic",
        },
        {
            ani: 4,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Știința materialelor",
        },
        {
            ani: 2,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria securității și sănătății în muncă",
        },
        {
            ani: 2,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria și managementul materialelor avansate",
        },
        {
            ani: 2,
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria sudării materialelor avansate",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Automatică și informatică aplicată",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Calculatoare",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Electronică aplicată",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Electrotehnică",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie electrică și calculatoare (în limba engleză)",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie electronică, telecomunicații și tehnologii informaționale ",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Robotică",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologia informației",
        },
        {
            ani: 4,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologii și sisteme de telecomunicații",
        },
        {
            ani: 2,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Securitate cibernetică",
        },
        {
            ani: 2,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme Avansate în Automatică și Tehnologii Informatice",
        },
        {
            ani: 2,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme electrice avansate (în limba engleză)",
        },
        {
            ani: 2,
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme electronice și de comunicații integrate",
        },
        {
            ani: 4,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Cinegetică",
        },
        {
            ani: 4,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Cinegetică",
        },
        {
            ani: 4,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Exploatări forestiere",
        },
        {
            ani: 4,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Măsurători terestre și cadastru",
        },
        {
            ani: 4,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Silvicultură",
        },
        {
            ani: 2,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management și sisteme tehnice în exploatări forestiere ",
        },
        {
            ani: 2,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Managementul ecosistemelor forestiere",
        },
        {
            ani: 2,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Silvicultură europeană",
        },
        {
            ani: 2,
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Silvicultură multifuncțională",
        },
        {
            ani: 4,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria prelucrării lemnului",
        },
        {
            ani: 4,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria și designul produselor finite din lemn",
        },
        {
            ani: 4,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie forestieră - Trunchi comun",
        },
        {
            ani: 4,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Ingineria prelucrării lemnului",
        },
        {
            ani: 2,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ecodesign de mobilier și restaurare",
        },
        {
            ani: 2,
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologia lemnului pentru constructii",
        },
        {
            ani: 4,
            fac: "07 Construcții",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Căi ferate, drumuri și poduri",
        },
        {
            ani: 4,
            fac: "07 Construcții",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Construcții civile, industriale și agricole",
        },
        {
            ani: 4,
            fac: "07 Construcții",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Instalații pentru construcții",
        },
        {
            ani: 2,
            fac: "07 Construcții",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Hazarduri naturale și evaluarea riscului în inginerie civilă",
        },
        {
            ani: 2,
            fac: "07 Construcții",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria construcțiilor sustenabile",
        },
        {
            ani: 2,
            fac: "07 Construcții",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Instalații pentru clădiri eficiente energetic",
        },
        {
            ani: 2,
            fac: "07 Construcții",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management de proiect în regenerarea urbană",
        },
        {
            ani: 2,
            fac: "07 Construcții",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Restaurarea și conservarea patrimoniului construit",
        },
        {
            ani: 4,
            fac: "08 Alimentație și Turism",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Controlul și expertiza produselor alimentare",
        },
        {
            ani: 4,
            fac: "08 Alimentație și Turism",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria produselor alimentare",
        },
        {
            ani: 4,
            fac: "08 Alimentație și Turism",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie și management în alimentația publică și agroturism",
        },
        {
            ani: 4,
            fac: "08 Alimentație și Turism",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie și management în industria turismului",
        },
        {
            ani: 2,
            fac: "08 Alimentație și Turism",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie gastronomică",
        },
        {
            ani: 2,
            fac: "08 Alimentație și Turism",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie și management în ospitalitatea de lux",
        },
        {
            ani: 2,
            fac: "08 Alimentație și Turism",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management în ospitalitate și eco-agro turism",
        },
        {
            ani: 2,
            fac: "08 Alimentație și Turism",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme de procesare și controlul calității produselor agroalimentare",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Design industrial",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Design industrial  (în limba engleză)",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria și protecția mediului în industrie",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Ingineria sistemelor de energii regenerabile",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Inginerie medicală",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Mecatronică",
        },
        {
            ani: 4,
            fac: "09 Design de Produs și Mediu",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Optometrie",
        },
        {
            ani: 2,
            fac: "09 Design de Produs și Mediu",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Design de produs pentru dezvoltare durabilă și protecția mediului ",
        },
        {
            ani: 2,
            fac: "09 Design de Produs și Mediu",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management integrat de mediu",
        },
        {
            ani: 2,
            fac: "09 Design de Produs și Mediu",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme mecatronice pentru industrie și medicină",
        },
        {
            ani: 3,
            fac: "10 Matematică Informatică",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Informatică",
        },
        {
            ani: 3,
            fac: "10 Matematică Informatică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Informatică",
        },
        {
            ani: 3,
            fac: "10 Matematică Informatică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Informatică aplicată",
        },
        {
            ani: 3,
            fac: "10 Matematică Informatică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Informatică aplicată (în limba germană)",
        },
        {
            ani: 3,
            fac: "10 Matematică Informatică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Matematică informatică",
        },
        {
            ani: 2,
            fac: "10 Matematică Informatică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Aplicații pentru telefonul mobil și tehnologii internet în E-business",
        },
        {
            ani: 2,
            fac: "10 Matematică Informatică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Structuri matematice fundamentale",
        },
        {
            ani: 2,
            fac: "10 Matematică Informatică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologii internet",
        },
        {
            ani: 2,
            fac: "10 Matematică Informatică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnologii moderne în ingineria sistemelor soft",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Limba și literatura română - o limba și literatură modernă (engleză, franceză)",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Limba și literatura chineză - o limbă și literatură modernă (engleză,franceză, germană)/limbă și literatură română)",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Limba și literatura engleză - o limbă și literatură modernă (franceză, germană)/Limba și literatura română)",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Limba și literatura română - o limbă și literatură modernă (engleză, franceză, germană)",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Limbi moderne aplicate",
        },
        {
            ani: 3,
            fac: "11 Litere",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Studii americane",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Cultură și discurs în spațiul anglo-american",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Inovare culturală",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Limbă și literatură română - identitate și multiculturalism",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Studii de limbă și cultură franceză",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Studii de limbă și literatură germană din perspectivă interculturală",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Studii de limba și literatura română",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Studii lingvistice pentru comunicare interculturală (în limba engleză)",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Cultură și discurs în spațiul anglo-american",
        },
        {
            ani: 2,
            fac: "11 Litere",
            cic: "Master",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Limbă și literatură română - identitate și multiculturalism",
        },
        {
            ani: 3,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Educație fizică și sportivă",
        },
        {
            ani: 3,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Kinetoterapie și motricitate specială",
        },
        {
            ani: 3,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Sport și performanță motrică",
        },
        {
            ani: 3,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Educație fizică și sportivă",
        },
        {
            ani: 3,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Sport și performanță motrică",
        },
        {
            ani: 2,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Educație fizică școlară și activități motrice de timp liber",
        },
        {
            ani: 2,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Leadership-ul fitness-ului și activităților recreative",
        },
        {
            ani: 2,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Performanță sportivă și management în sport",
        },
        {
            ani: 2,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Performanță umană în antrenamentul sportiv",
        },
        {
            ani: 2,
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Profilaxie și recuperare motrică și somato-funcțională prin exercițiu fizic",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Afaceri internaționale",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Contabilitate și informatică de gestiune",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Economia comerțului, turismului și serviciilor",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Management",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Marketing",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Administrarea afacerilor (în limba engleză)",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Afaceri internaționale",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Contabilitate și informatică de gestiune",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Economia comerțului, turismului și serviciilor",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Finanțe și bănci",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Informatică economică",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Management",
        },
        {
            ani: 3,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Marketing",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Administrarea afacerilor în turism",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management financiar bancar",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Management și strategii de afaceri ",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Politici contabile, audit și control de gestiune",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Politici și strategii de marketing",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Relații economice internaționale",
        },
        {
            ani: 2,
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme informatice integrate pentru afaceri",
        },
        {
            ani: 3,
            fac: "14 Psihologie și Științele Educației",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Pedagogia învățământului primar și preșcolar",
        },
        {
            ani: 3,
            fac: "14 Psihologie și Științele Educației",
            cic: "Licență",
            frm: "Învățământ la Distanță",
            prg: "Psihologie",
        },
        {
            ani: 3,
            fac: "14 Psihologie și Științele Educației",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Pedagogia învățământului primar și preșcolar",
        },
        {
            ani: 3,
            fac: "14 Psihologie și Științele Educației",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Psihologie",
        },
        {
            ani: 3,
            fac: "14 Psihologie și Științele Educației",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Psihopedagogie specială",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Educație și consiliere în context intercultural",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Formarea și managementul resurselor umane în educație",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Psihologia muncii, organizațională și resurse umane",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Psihologie clinică, consiliere psihologică și psihoterapie",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Psihologie educațională, consiliere școlară și vocațională",
        },
        {
            ani: 2,
            fac: "14 Psihologie și Științele Educației",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Psihopedagogia educației timpurii și a școlarității mici",
        },
        {
            ani: 4,
            fac: "15 Drept",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Drept",
        },
        {
            ani: 4,
            fac: "15 Drept",
            cic: "Licență",
            frm: "Învățământ cu Frecvență Redusă",
            prg: "Drept",
        },
        {
            ani: 2,
            fac: "15 Drept",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Drept privat aprofundat",
        },
        {
            ani: 2,
            fac: "15 Drept",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Drept și diplomația dezvoltării durabile",
        },
        {
            ani: 2,
            fac: "15 Drept",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Legislație europeană și carieră judiciară",
        },
        {
            ani: 2,
            fac: "15 Drept",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Sisteme și instituții de drept internațional și european",
        },
        {
            ani: 2,
            fac: "15 Drept",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Științe penale aprofundate",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Asistență socială",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Comunicare și relatii publice",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Media digitală",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Media digitală (în limba engleză)",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Resurse umane",
        },
        {
            ani: 3,
            fac: "16 Sociologie și Comunicare",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Sociologie",
        },
        {
            ani: 2,
            fac: "16 Sociologie și Comunicare",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Asistență și dezvoltare comunitară",
        },
        {
            ani: 2,
            fac: "16 Sociologie și Comunicare",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Gestiunea campaniilor de imagine",
        },
        {
            ani: 2,
            fac: "16 Sociologie și Comunicare",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Gestiunea și dezvoltarea resursei umane",
        },
        {
            ani: 4,
            fac: "17 Medicină",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Asistență medicală generală",
        },
        {
            ani: 3,
            fac: "17 Medicină",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Balneofiziokinetoterapie și recuperare",
        },
        {
            ani: 3,
            fac: "17 Medicină",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Laborator clinic",
        },
        {
            ani: 6,
            fac: "17 Medicină",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Medicină",
        },
        {
            ani: 2,
            fac: "17 Medicină",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Managementul și strategiile îngrijirilor paliative",
        },
        {
            ani: 2,
            fac: "17 Medicină",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Managementul strategiilor preventive și politici de sănătate",
        },
        {
            ani: 2,
            fac: "17 Medicină",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Medicină tradițională chineză",
        },
        {
            ani: 4,
            fac: "18 Muzică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Interpretare muzicală - canto",
        },
        {
            ani: 4,
            fac: "18 Muzică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Interpretare muzicală - instrumente",
        },
        {
            ani: 4,
            fac: "18 Muzică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Interpretare muzicală - instrumente (în limba engleză)",
        },
        {
            ani: 3,
            fac: "18 Muzică",
            cic: "Licență",
            frm: "Învățământ cu Frecvență",
            prg: "Muzică",
        },
        {
            ani: 2,
            fac: "18 Muzică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Meloterapie",
        },
        {
            ani: 2,
            fac: "18 Muzică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Stil și performanță în interpretarea instrumentală și vocală",
        },
        {
            ani: 2,
            fac: "18 Muzică",
            cic: "Master",
            frm: "Învățământ cu Frecvență",
            prg: "Tehnica și arta muzicală din sec. al XX-lea",
        },
    ],
};
