export default {
    antet: [
        "Facultatea",
        "Ciclul de studii",
        "Forma de invatamant",
        "Programul de studii",
    ],
    facultati: [
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Autovehicule rutiere",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Autovehicule rutiere (în limba engleză)",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria transporturilor şi a traficului",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie mecanică",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IFR",
            prg: "Autovehicule rutiere",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "LICENȚĂ",
            frm: "IFR",
            prg: "Inginerie mecanică",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Autovehiculul și mediul",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Autovehiculul și tehnologiile viitorului",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Inginerie virtuală în proiectarea autovehiculelor",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Metode practice integrate in ingineria sistemelor de propulsie",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Securitate rutieră, transport și interacțiunea cu mediul",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Simulare şi testare în inginerie mecanică",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme de comandă și control pentru autovehicule",
        },
        {
            fac: "01 Inginerie Mecanică",
            cic: "MASTER",
            frm: "IFR",
            prg: "Autovehiculul și mediul",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Inginerie economică industrială",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Construcţii aerospaţiale",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria şi managementul afacerilor",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria şi managementul calităţii",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie economică industrială",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Sisteme de producţie digitale",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Tehnologia construcţiilor de maşini",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria fabricației inovative",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria proceselor de fabricație avansate",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "MASTER",
            frm: "IF",
            prg: "Inginerie și management în aviație",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "MASTER",
            frm: "IF",
            prg: "Managementul afacerilor în industrie",
        },
        {
            fac: "02 Inginerie Tehnologică și Management Industrial",
            cic: "MASTER",
            frm: "IF",
            prg: "Managementul calităţii",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Antreprenoriat în ingineria materialelor",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria securităţii în industrie",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria sudării",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie economică în domeniul mecanic",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Știința materialelor",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria securităţii şi sănătăţii în muncă",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria şi managementul materialelor avansate",
        },
        {
            fac: "03 Știinta și Ingineria Materialelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria sudării materialelor avansate",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Automatică şi informatică aplicată",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Calculatoare",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Electronică aplicată",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Electrotehnică",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie electrică şi calculatoare (în limba engleză)",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie electronică, telecomunicații și tehnologii informaționale",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Robotică",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Tehnologia informaţiei",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Tehnologii şi sisteme de telecomunicaţii",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Securitate cibernetică",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme Avansate în Automatică şi Tehnologii Informatice",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme electrice avansate (în limba engleză)",
        },
        {
            fac: "04 Inginerie Electrică și Știința Calculatoarelor",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme electronice şi de comunicaţii integrate",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Cinegetică",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Cinegetică",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Exploatări forestiere",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Măsurători terestre şi cadastru",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Silvicultură",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Silvicultură (trunchi comun)",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "MASTER",
            frm: "IF",
            prg: "Management și sisteme tehnice în exploatări forestiere",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "MASTER",
            frm: "IF",
            prg: "Managementul ecosistemelor forestiere",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "MASTER",
            frm: "IF",
            prg: "Silvicultură europeană",
        },
        {
            fac: "05 Silvicultură și Exploatări Forestiere",
            cic: "MASTER",
            frm: "IF",
            prg: "Silvicultură multifuncțională",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria prelucrării lemnului",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria şi designul produselor finite din lemn",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie forestieră - Trunchi comun",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "LICENȚĂ",
            frm: "IFR",
            prg: "Ingineria prelucrării lemnului",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "MASTER",
            frm: "IF",
            prg: "Ecodesign de mobilier şi restaurare",
        },
        {
            fac: "06 Design de Mobilier și Inginerie a Lemnului",
            cic: "MASTER",
            frm: "IF",
            prg: "Tehnologia lemnului pentru constructii",
        },
        {
            fac: "07 Construcții",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Căi ferate, drumuri şi poduri",
        },
        {
            fac: "07 Construcții",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Construcţii civile, industriale şi agricole",
        },
        {
            fac: "07 Construcții",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Instalaţii pentru construcţii",
        },
        {
            fac: "07 Construcții",
            cic: "MASTER",
            frm: "IF",
            prg: "Hazarduri naturale și evaluarea riscului în inginerie civilă",
        },
        {
            fac: "07 Construcții",
            cic: "MASTER",
            frm: "IF",
            prg: "Ingineria construcțiilor sustenabile",
        },
        {
            fac: "07 Construcții",
            cic: "MASTER",
            frm: "IF",
            prg: "Instalații pentru clădiri eficiente energetic",
        },
        {
            fac: "07 Construcții",
            cic: "MASTER",
            frm: "IF",
            prg: "Management de proiect în regenerarea urbană",
        },
        {
            fac: "07 Construcții",
            cic: "MASTER",
            frm: "IF",
            prg: "Restaurarea și conservarea patrimoniului construit",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Controlul şi expertiza produselor alimentare",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria produselor alimentare",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie şi management în alimentaţia publică şi agroturism",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie şi management în industria turismului",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "MASTER",
            frm: "IF",
            prg: "Inginerie gastronomică",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "MASTER",
            frm: "IF",
            prg: "Inginerie și management în ospitalitatea de lux",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "MASTER",
            frm: "IF",
            prg: "Management în ospitalitate și eco-agro turism",
        },
        {
            fac: "08 Alimentație și Turism",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme de procesare și controlul calității produselor agroalimentare",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Design industrial",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Design industrial  (în limba engleză)",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria şi protecţia mediului în industrie",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Ingineria sistemelor de energii regenerabile",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Inginerie medicală",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Mecatronică",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Optometrie",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "MASTER",
            frm: "IF",
            prg: "Design de produs pentru dezvoltare durabilă și protecția mediului",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "MASTER",
            frm: "IF",
            prg: "Management integrat de mediu",
        },
        {
            fac: "09 Design de Produs și Mediu",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme mecatronice pentru industrie și medicină",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Informatică",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Informatică",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Informatică aplicată",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Informatică aplicată (în limba germană)",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Matematică informatică",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "MASTER",
            frm: "IF",
            prg: "Aplicaţii pentru telefonul mobil şi tehnologii internet în E-business",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "MASTER",
            frm: "IF",
            prg: "Structuri matematice fundamentale",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "MASTER",
            frm: "IF",
            prg: "Tehnologii internet",
        },
        {
            fac: "10 Matematică Informatică",
            cic: "MASTER",
            frm: "IF",
            prg: "Tehnologii moderne în ingineria sistemelor soft",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Limba şi literatura română - o limba şi literatură modernă (engleză, franceză)",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Limba şi literatura chineză - o limbă şi literatură modernă (engleză,franceză, germană)/limbă şi literatură română)",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Limba şi literatura engleză - o limbă şi literatură modernă (franceză, germană)/Limba şi literatura română)",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Limba şi literatura română - o limbă şi literatură modernă (engleză, franceză, germană)",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Limbi moderne aplicate",
        },
        {
            fac: "11 Litere",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Studii americane",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Cultură şi discurs în spaţiul anglo-american",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Inovare culturală",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Limbă şi literatură română - identitate şi multiculturalism",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Studii de limbă și cultură franceză",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Studii de limbă și literatură germană din perspectivă interculturală",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Studii de limba şi literatura română",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IF",
            prg: "Studii lingvistice pentru comunicare interculturală (în limba engleză)",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IFR",
            prg: "Cultură şi discurs în spaţiul anglo-american",
        },
        {
            fac: "11 Litere",
            cic: "MASTER",
            frm: "IFR",
            prg: "Limbă şi literatură română - identitate şi multiculturalism",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Educație fizică și sportivă",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Kinetoterapie și motricitate specială",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Sport și performanță motrică",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "LICENȚĂ",
            frm: "IFR",
            prg: "Educație fizică și sportivă",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "LICENȚĂ",
            frm: "IFR",
            prg: "Sport și performanță motrică",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "MASTER",
            frm: "IF",
            prg: "Educație fizică școlară și activități motrice de timp liber",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "MASTER",
            frm: "IF",
            prg: "Leadership-ul fitness-ului și activităților recreative",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "MASTER",
            frm: "IF",
            prg: "Performanță sportivă și management în sport",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "MASTER",
            frm: "IF",
            prg: "Performanță umană în antrenamentul sportiv",
        },
        {
            fac: "12 Educație Fizică și Sporturi Montane",
            cic: "MASTER",
            frm: "IF",
            prg: "Profilaxie și recuperare motrică și somato-funcțională prin exercițiu fizic",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Afaceri internaţionale",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Contabilitate şi informatică de gestiune",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Economia comerţului, turismului şi serviciilor",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Management",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Marketing",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Administrarea afacerilor (în limba engleză)",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Afaceri internaţionale",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Contabilitate şi informatică de gestiune",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Economia comerţului, turismului şi serviciilor",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Finanţe şi bănci",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Informatică economică",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Management",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Marketing",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Administrarea afacerilor în turism",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Management financiar bancar",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Management și strategii de afaceri",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Politici contabile, audit și control de gestiune",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Politici și strategii de marketing",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Relaţii economice internaționale",
        },
        {
            fac: "13 Științe Economice și Administrarea Afacerilor",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme informatice integrate pentru afaceri",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Pedagogia învăţământului primar şi preşcolar",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "LICENȚĂ",
            frm: "ID",
            prg: "Psihologie",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Pedagogia învăţământului primar şi preşcolar",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Psihologie",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Psihopedagogie specială",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Educație și consiliere în context intercultural",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Formarea și managementul resurselor umane în educație",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Psihologia muncii, organizațională și resurse umane",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Psihologie clinică, consiliere psihologică și psihoterapie",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Psihologie educațională, consiliere școlară și vocațională",
        },
        {
            fac: "14 Psihologie și Științele Educației",
            cic: "MASTER",
            frm: "IF",
            prg: "Psihopedagogia educaţiei timpurii şi a şcolarităţii mici",
        },
        { fac: "15 Drept", cic: "LICENȚĂ", frm: "IF", prg: "Drept" },
        { fac: "15 Drept", cic: "LICENȚĂ", frm: "IFR", prg: "Drept" },
        {
            fac: "15 Drept",
            cic: "MASTER",
            frm: "IF",
            prg: "Drept privat aprofundat",
        },
        {
            fac: "15 Drept",
            cic: "MASTER",
            frm: "IF",
            prg: "Drept și diplomația dezvoltării durabile",
        },
        {
            fac: "15 Drept",
            cic: "MASTER",
            frm: "IF",
            prg: "Legislație europeană și carieră judiciară",
        },
        {
            fac: "15 Drept",
            cic: "MASTER",
            frm: "IF",
            prg: "Sisteme și instituții de drept internațional și european",
        },
        {
            fac: "15 Drept",
            cic: "MASTER",
            frm: "IF",
            prg: "Științe penale aprofundate",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Asistență socială",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Comunicare și relatii publice",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Media digitală",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Media digitală (în limba engleză)",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Resurse umane",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Sociologie",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "MASTER",
            frm: "IF",
            prg: "Asistență și dezvoltare comunitară",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "MASTER",
            frm: "IF",
            prg: "Gestiunea campaniilor de imagine",
        },
        {
            fac: "16 Sociologie și Comunicare",
            cic: "MASTER",
            frm: "IF",
            prg: "Gestiunea și dezvoltarea resursei umane",
        },
        {
            fac: "17 Medicină",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Asistenţă medicală generală",
        },
        {
            fac: "17 Medicină",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Balneofiziokinetoterapie şi recuperare",
        },
        {
            fac: "17 Medicină",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Laborator clinic",
        },
        { fac: "17 Medicină", cic: "LICENȚĂ", frm: "IF", prg: "Medicină" },
        {
            fac: "17 Medicină",
            cic: "MASTER",
            frm: "IF",
            prg: "Managementul și strategiile îngrijirilor paliative",
        },
        {
            fac: "17 Medicină",
            cic: "MASTER",
            frm: "IF",
            prg: "Managementul strategiilor preventive și politici de sănătate",
        },
        {
            fac: "17 Medicină",
            cic: "MASTER",
            frm: "IF",
            prg: "Medicină tradițională chineză",
        },
        {
            fac: "18 Muzică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Interpretare muzicală - canto",
        },
        {
            fac: "18 Muzică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Interpretare muzicală - instrumente",
        },
        {
            fac: "18 Muzică",
            cic: "LICENȚĂ",
            frm: "IF",
            prg: "Interpretare muzicală - instrumente (în limba engleză)",
        },
        { fac: "18 Muzică", cic: "LICENȚĂ", frm: "IF", prg: "Muzică" },
        { fac: "18 Muzică", cic: "MASTER", frm: "IF", prg: "Meloterapie" },
        {
            fac: "18 Muzică",
            cic: "MASTER",
            frm: "IF",
            prg: "Stil și performanță în interpretarea instrumentală și vocală",
        },
        {
            fac: "18 Muzică",
            cic: "MASTER",
            frm: "IF",
            prg: "Tehnica și arta muzicală din sec. al XX-lea",
        },
    ],
};
